# Generated by Django 3.2.8 on 2021-11-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default=None, max_length=30, verbose_name='Город'),
            preserve_default=False,
        ),
    ]
